version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
    run:
      description: Build application with Release configuration
      executor:
        name: windows/default
